// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olyozgenxsccrodcfetf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9seW96Z2VueHNjY3JvZGNmZXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjk2NjIsImV4cCI6MjA2NTYwNTY2Mn0.0FxkzeZ0mYVbGYmwUmsibCaBa6vUIVAF65YRXXknuBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);