
-- Criar tabela para certificados
CREATE TABLE public.certificados (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_certificado TEXT NOT NULL,
  arquivo_pdf TEXT,
  data_emissao DATE NOT NULL,
  data_registro TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Comentários para documentar a tabela
COMMENT ON TABLE public.certificados IS 'Tabela para armazenar certificados com PDFs';
COMMENT ON COLUMN public.certificados.nome_certificado IS 'Nome do certificado';
COMMENT ON COLUMN public.certificados.arquivo_pdf IS 'URL do arquivo PDF no Supabase Storage';
COMMENT ON COLUMN public.certificados.data_emissao IS 'Data de emissão do certificado';
COMMENT ON COLUMN public.certificados.data_registro IS 'Data de registro no sistema';
